### ISSUE TITLE
May be create a first release?

### ISSUE THREAD

**Issue by roquie** [galexrt/ansible-ntpdate#2]
It's a best practice. Install from origin/master is a bad idea.

**Comment by galexrt** [comment]
Thanks for the heads up! I totally forgot to create a tag. Here you go: https://github.com/galexrt/ansible-ntpdate/releases/tag/v1.0.0

If there is anything else to improve, please let me know!

***

Closing as issue has been resolved.

**Comment by roquie** [comment]
Thx, Alexander!
